server:
  port: 8081

spring.application.name: ORDER_SERVICE

eureka:
  instance:
    leaseRenewalInterval: 10
    leaseExperationDurationinSecond: 20
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 50
